name: Build and Run

on:

  push:

    branches: [ master ]

  pull_request:

    branches: [ master ]

jobs:

  build:

    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v2
  
    - name: run receiver locally
      run: cd Receiver && ./stor_scp.exe -p 6767 -s
