name: Build and Run

on:

  push:

    branches: [ master ]

  pull_request:

    branches: [ master ]

jobs:

  build:

    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v2

    - name: build Sender(MedicalDevice)
      run: g++ Sender\*.cpp -I mc3inc -L mc3lib -l jansson -l libxml2 -l mc3adll64 -l mc3adll64d -l mc3adv64 -l picxm -o sender
  
    # - name: run receiver locally
    #   run: cd Receiver && ./stor_scp.exe -p 6767 -s
   
   
    - name: build senderTestApplication
      run: g++ SenderTest\*.cpp -I mc3inc -L mc3lib -l jansson -l libxml2 -l mc3adll64 -l mc3adll64d -l mc3adv64 -l picxm --coverage -o senderTestApp
      
    - name: move gcno to sender test dir
      run: move *.gcno SenderTest 

    - name: move senderTestApp to mc3lib
      run: move senderTestApp.exe mc3lib
    
    - name: cd into mc3lib to run sender
      run: cd mc3lib && ./senderTestApp.exe 

    - name: move .gcda files to sender test dir
      run:  move *.gcda SenderTest

    - name: sender coverage report(ImageListTest)
      run:  gcov -r SenderTest/ImageListTest.cpp
      
    - name: sender coverage report(ImageList)
      run:  gcov -r SenderTest/ImageList.cpp
      
    - name: sender coverage report(ReadImage)
      run:  gcov -r SenderTest/ReadImage.cpp
      
    - name: sender coverage report(SendImage)
      run:  gcov -r SenderTest/SendImage.cpp
      
    - name: sender coverage report(general_util)
      run:  gcov -r SenderTest/general_util.cpp
    
    - name: sender coverage report(SenderMainFunctions)
      run:  gcov -r SenderTest/SenderMainFunctions.cpp
