name: Build and Test

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'
jobs:

  build: 

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2 
      with:
          vs-version: 15.0
    
    - name: msbuild Project build
      run: MSBuild.exe D:\a\transfer-images-s1b7\transfer-images-s1b7\SenderTest1\TransferMedicalimages.vcxproj /p:configuration=debug /p:platform=x64
    
    - name: msBuild Run
      run: D:\a\transfer-images-s1b7\transfer-images-s1b7\SenderTest1\x64\debug\TransferMedicalimages.exe
   

    - name: build senderTestApplication
      run: g++ SenderTest\ImageListTest.cpp -I mc3inc -L mc3lib -l jansson -l libxml2 -l mc3adll64 -l mc3adll64d -l mc3adv64 -l picxm --coverage -o senderTestApp
   
    - name: move gcno to sender test dir
      run: move *.gcno SenderTest1 
         
    # - name: run python script locally
    #   run: cd EmailSender && python filepolling.py

    - name: move senderTestApp to mc3lib
      run: move senderTestApp.exe mc3lib
    
    - name: cd into mc3lib to run sender
      run: cd mc3lib && ./senderTestApp.exe 

    - name: move .gcda files to sender test dir
      run:  move *.gcda SenderTest1

    - name: sender coverage report
      run:  gcov -r SenderTest1\*.cpp

