name: Limit complexity and Static Analysis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: install cppcheck static analysis
      run: sudo apt-get update && sudo apt-get install -y cppcheck

    - name: Static Analysis on Sender Folder files
      run: cppcheck sender/*.cpp

    - name: Install lizard
      run: pip install lizard

    - name: Limit complexity
      run: $HOME/.local/bin/lizard --CCN 3 -x"./SenderTest1/catch.hpp" -x"./mc3inc/*"
